### ISSUE TITLE
fix/front/traduction-non-persistant

### ISSUE THREAD

**Issue by Polipoppy** [BeyondVisionAI/web_application#111]
Lorsque je mets en français, puis que je clique sur le bouton pour me log in, le site repasse en anglais, alors qu'il faudrait que ça reste en français

**Comment by Polipoppy** [comment]
Pareil pour le dashboard

**Comment by MinMatth-Magi** [comment]
> Lorsque je mets en français, puis que je clique sur le bouton pour me log in, le site repasse en anglais, alors qu'il faudrait que ça reste en français

Toutes les pages d'auth ainsi que d'autres parties du projet sont traduites sur la branche i18n-everywhere, avec la refont dashboard je ne pouvais pas encore traduire cette partie
